const JENIS_SURAT_OPTIONS = [
  'SURAT KELUAR UMUM',
  'SURAT KELUAR YANKUM',
  'SURAT KELUAR P2L',
  'SK KAKANWIL',
  'SURAT PERINTAH',
  'SURAT CUTI'
];

const STATUS = {
  PENDING: '0',
  APPROVED: '1',
  REJECTED: '2'
};

const USER_ROLES = Object.freeze({
  ADMIN: 1,
  SUPER_ADMIN: 2
});

module.exports = { JENIS_SURAT_OPTIONS, STATUS, USER_ROLES };
