export const JENIS_SURAT_OPTIONS = [
  'BUKU KELUAR UMUM',
  'SK KAKANWIL',
  'BUKU KELUAR YANKUM',
  'BUKU MASUK UMUM',
  'BUKU SURAT PERINTAH',
  'BUKU CUTI',
  'BUKU KELUAR PLH/PLT',
  'BUKU KELUAR P2L',
  'BUKU MASUK P2L',
  'BUKU MASUK YANKUM'
];

export const RUANG_OPTIONS = [
  'PERENCANAAN',
  'ORGANISASI DAN TATA LAKSANA',
  'KEPEGAWAIAN',
  'KEUANGAN',
  'PENGELOLAAN BARANG MILIK NEGARA',
  'KEHUMASAN DAN HUKUM',
  'UMUM',
  'PENGAWASAN',
  'TEKNOLOGI DAN INFORMASI',
  'PERATURAN PERUNDANG-UNDANGAN',
  'ADMINISTRASI HUKUM UMUM',
  'KEKAYAAN INTELEKTUAL',
  'PEMBINAAN HUKUM NASIONAL',
  'SUMBER DAYA MANUSIA',
  'PENELITIAN DAN PENGEMBANGAN'
];

export const STATUS = {
  PENDING: '0',
  APPROVED: '1',
  REJECTED: '2'
};
